### PR TITLE
Change regex for valid webId

### PR DESCRIPTION
**Pull request by jaxoncreed**

### CODE REVIEW

**Comment by james-martin-jd** [comment]
One minor request, can we change the regex to allow http to be case insensitive? This request comes after someone tried to manually type their webid in via an iphone, which automatically capitalizes the first word (so it was Http://... instead of http://...)

**Comment by megoth** [comment]
Good point on capitalization - then we also need to make sure that we normalize the input properly (basically cast the string to lowercase)

**Comment by jaxoncreed** [comment]
Isn't it already case insensitive because of the 'i' parameter later in the Regex constructor?

**Comment by james-martin-jd** [comment]
Hmm, you're right, it should. Someone said it wasn't working. I'll merge and test it in the generator.

**Pull request merged**
