### PR TITLE
Explain how to develop

### LINKED ISSUE #137: npm install fails
it seems that when you check out this repo and run `npm install`, there are a number of errors like:
```sh
npm WARN tar ENOENT: no such file or directory, open '/Users/michiel/gh/inrupt/solid-react-components/node_modules/.staging/...
```

With `yarn install` it works better, but still seeing this one:
```sh
error An unexpected error occurred: "https://registry.npmjs.org/solid-forms: Not found".
```

### PR DESCRIPTION
**Pull request by michielbdejong**
Fixes #137

### CODE REVIEW

**Comment by james-martin-jd** [comment]
We are addressing this issue a different way starting soon (tomorrow is likely) so the instructions should actually remain the same.

We thought about making master the recommended branch, but since it can often be behind, it would lead to duplicate issues, lots of merge conflicts, and a generally unpleasant dev experience.

**Comment by michielbdejong** [comment]
Ah ok, great! So I just tried it out and the (default) develop branch works now, so no need to switch to master anymore. Still, I think it would be nice to have a 'Develop' section in the readme to get external contributors on their way?

**Comment by james-martin-jd** [comment]
We do already have a contributing guideline here: https://github.com/inrupt/solid-react-sdk/blob/master/CONTRIBUTING.md#getting-started which is linked from this repo (and the generator as well). It doesn't explain how to clone a repo, for example, but I don't think it's our place to teach how to use github.

**Comment by michielbdejong** [comment]
Ah great! Found it, https://github.com/inrupt/solid-react-components/blob/develop/CONTRIBUTING.md, not sure why I missed that earlier. OK then we can close this one, thanks!

**Pull request closed without merging**
